#!/usr/bin/env python3
"""
Regenerate the Questionnaire Battery wiki pages from the battery Excel file.

Source of truth : data/Coventure_Battery_2020-07-27.xlsx  (gitignored, never committed)
Output          : docs/datasets/questionnaire-battery/
                  - index.md              (visible overview, listed in nav)
                  - scales/<code>.md      (one hidden page per questionnaire scale)
                  - derived-variables.md  (hidden: computed/derived variable formulas)
                  - tasks.md              (hidden: cognitive task variables)

Only index.md is listed in mkdocs.yml `nav:`; the rest are built and searchable
but do not appear in the sidebar.

Usage:
    python3 scripts/build_battery_pages.py
Run this whenever the Excel file changes, then commit the regenerated pages.
"""

import html
import re
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
EXCEL_PATH = REPO_ROOT / "data" / "Coventure_Battery_2020-07-27.xlsx"
OUT_DIR = REPO_ROOT / "docs" / "datasets" / "questionnaire-battery"
SCALES_DIR = OUT_DIR / "scales"

DICT_PAGE = "../data-dictionaries/coventure-neuroventure.md"

# Scale code -> (display name, anchor of its entry in the data dictionary page)
SCALES = {
    "DEM_":         ("Demographics",                                   "dem_-demographics"),
    "SURPS_":       ("Substance Use Risk Profile Scale",               "surps_-substance-use-risk-profile-scale"),
    "DEPAPO_":      ("DEP-ADO — substance use screening",              "depapo_-dep-ado-substance-use-screening"),
    "DMQ_":         ("Drinking Motives Questionnaire",                 "dmq_-drinking-motives-questionnaire"),
    "CMQ_":         ("Cannabis Motives Questionnaire",                 "cmq_-cannabis-motives-questionnaire"),
    "SDQ_":         ("Strengths and Difficulties Questionnaire",       "sdq_-strengths-and-difficulties-questionnaire"),
    "BSI_":         ("Brief Symptom Inventory (subset)",               "bsi_-brief-symptom-inventory-subset"),
    "COPE_":        ("Brief COPE Inventory",                           "cope_-brief-cope-inventory"),
    "PSYCHOTIC_":   ("Psychotic-like experiences screen (APSS)",       "psychotic_-psychotic-like-experiences-screen"),
    "SOC_NORMS_":   ("Perceived Social Norms",                         "soc_norms_-perceived-social-norms"),
    "SELF_ESTEEM_": ("Rosenberg Self-Esteem Scale",                    "self_esteem_-rosenberg-self-esteem-scale"),
    "BULLY_":       ("Bullying involvement questionnaire",             "bully_-bullying-involvement-questionnaire"),
    "Sleep_":       ("Sleep habits questionnaire",                     "sleep_-sleep-habits-questionnaire"),
    "EAT_":         ("Eating habits questionnaire",                    "eat_-eating-habits-questionnaire"),
    "AUTO_":        ("Children's Automatic Thoughts Scale",            "auto_-automatic-thoughts-questionnaire"),
}

TASKS = {
    "CMS":  ("Children's Memory Scale ('Dot Location' test)", "cms-memory-task"),
    "SWM":  ("Spatial Working Memory",                        "swm-spatial-working-memory"),
    "CFT":  ("Culture Fair (non-verbal IQ) test",             "cft-culture-fair-non-verbal-iq-test"),
    "PALP": ("Probabilistic Associative Learning Paradigm",   "palp-probabilistic-associative-learning-paradigm"),
}

# Items-sheet columns (positional, per the 'Item_code' header row)
ITEM_COLS = ["code", "question_en", "levels", "answers_en",
             "question_fr", "levels_fr", "answers_fr", "subscale", "skip_rule"]

GENERATED_NOTE = (
    "<!-- Auto-generated by scripts/build_battery_pages.py from "
    "data/Coventure_Battery_2020-07-27.xlsx — do not edit by hand. -->\n\n"
)

# Cells longer than this get a collapsed "see more" preview (click to expand).
SEE_MORE_AT = 140
PREVIEW_LEN = 90


def cell(value) -> str:
    """Render an Excel cell as Markdown-table-safe text (empty -> em dash).

    Long content is collapsed behind a clickable <details> preview so table
    rows stay readable.
    """
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return "—"
    raw = str(value).strip()
    if not raw:
        return "—"
    body = raw.replace("|", "\\|").replace("\r\n", "\n").replace("\n", "<br>")
    if len(raw) > SEE_MORE_AT:
        preview = html.escape(re.sub(r"\s+", " ", raw)[:PREVIEW_LEN].strip())
        return f"<details><summary>{preview}&hellip;</summary>{body}</details>"
    return body


def slug(code: str) -> str:
    """File slug for a scale code (DEM_ -> dem, SOC_NORMS_ -> soc_norms)."""
    return code.rstrip("_").lower()


def parse_items_sheet(xl: pd.ExcelFile):
    """
    Parse the 'Items' sheet into per-scale blocks.

    A block starts at a row whose first cell is a bare scale code (ends with '_',
    no digits); the next row repeats the column headers. Rows with text but no
    item code are instructions; QC_* rows are quality-control variables.

    Returns {scale_code: {"instructions": [(en, fr)], "items": [dict], "qc": [dict]}}
    """
    df = xl.parse("Items", header=None)
    df.columns = range(df.shape[1])

    def is_block_header(row) -> bool:
        v = row[0]
        return (
            isinstance(v, str)
            and v.strip() in SCALES
            and pd.isna(row[1])
            or (isinstance(v, str) and v.strip() in SCALES and str(row[1]).strip() == "English version")
        )

    blocks: dict[str, dict] = {}
    current: str | None = None
    for _, row in df.iterrows():
        row = row.tolist() + [None] * (len(ITEM_COLS) - df.shape[1])
        if is_block_header(row):
            current = str(row[0]).strip()
            blocks[current] = {"instructions": [], "items": [], "qc": []}
            continue
        if current is None:
            continue
        code = row[0]
        if isinstance(code, str) and code.strip() == "Item_code":
            continue  # repeated column-header row at the top of each block
        record = dict(zip(ITEM_COLS, row))
        if pd.isna(code) or not str(code).strip():
            # Instruction / preamble row (no item code, has question text)
            en, fr = record["question_en"], record["question_fr"]
            if pd.notna(en) or pd.notna(fr):
                blocks[current]["instructions"].append(
                    ("" if pd.isna(en) else str(en).strip(),
                     "" if pd.isna(fr) else str(fr).strip()))
            continue
        record["code"] = str(code).strip()
        if record["code"].startswith("QC_"):
            blocks[current]["qc"].append(record)
        else:
            blocks[current]["items"].append(record)
    return blocks


def render_scale_page(code: str, block: dict) -> str:
    name, anchor = SCALES[code]
    n_items = len(block["items"])
    parts = [GENERATED_NOTE]
    parts.append(f"# {code.rstrip('_')} — {name}\n")
    meta = f"{n_items} items"
    if block["qc"]:
        meta += f" · {len(block['qc'])} quality-control variable(s)"
    parts.append(f"> {meta} · Source: `{EXCEL_PATH.name}`\n")
    parts.append(
        f"[← Back to Battery overview](../index.md) · "
        f"[Data dictionary entry](../{DICT_PAGE}#{anchor})\n")

    for en, fr in block["instructions"]:
        parts.append("\n**Instructions (EN):** " + en.replace("\n", " ") + "\n")
        if fr:
            parts.append("\n**Instructions (FR):** " + fr.replace("\n", " ") + "\n")

    header = ("| # | Variable | Question (EN) | Responses (EN) | Question (FR) "
              "| Réponses (FR) | Subscale | Skip rule |\n"
              "|---|---|---|---|---|---|---|---|\n")
    rows = []
    for i, r in enumerate(block["items"], start=1):
        rows.append(
            f"| {i} | `{cell(r['code'])}` | {cell(r['question_en'])} | {cell(r['answers_en'])} "
            f"| {cell(r['question_fr'])} | {cell(r['answers_fr'])} "
            f"| {cell(r['subscale'])} | {cell(r['skip_rule'])} |\n")
    parts.append("\n## Items\n\n" + header + "".join(rows))

    if block["qc"]:
        parts.append("\n## Quality-control variables\n\n")
        parts.append("| Variable | Note |\n|---|---|\n")
        for r in block["qc"]:
            parts.append(f"| `{cell(r['code'])}` | {cell(r['question_en'])} |\n")
    return "\n".join(p if p.endswith("\n") else p + "\n" for p in parts)


def parse_generic_blocks(df: pd.DataFrame):
    """
    Split a sheet into blocks the same way as the Items sheet: a block starts
    with a row whose first cell has no digits and whose second cell is a label
    or empty, followed by a small header row. Returns {block_name: (header, rows)}.
    """
    blocks = {}
    i = 0
    n = len(df)
    while i < n:
        first = df.iloc[i, 0]
        if pd.notna(first) and isinstance(first, str):
            name = first.strip()
            # header row expected at i+1
            if i + 1 < n:
                header = [str(v).strip() for v in df.iloc[i + 1].tolist() if pd.notna(v)]
                rows = []
                j = i + 2
                while j < n:
                    v = df.iloc[j]
                    if pd.isna(v[0]) and v.isna().all():
                        j += 1
                        break
                    # stop at next block: col0 text without digits AND col1 empty or new header follows
                    if (pd.notna(v[0]) and isinstance(v[0], str)
                            and not re.search(r"\d", str(v[0]))
                            and (pd.isna(v[1]) or str(v.iloc[0]).strip() in TASKS or str(v.iloc[0]).strip() in SCALES)
                            and str(v[0]).strip() not in ("Subscale",)):
                        break
                    if pd.notna(v[0]):
                        rows.append(v.tolist())
                    j += 1
                blocks[name] = (header, rows)
                i = j
                continue
        i += 1
    return blocks


def render_derived_page(xl: pd.ExcelFile) -> str:
    df = xl.parse("Derived variables", header=None)
    blocks = parse_generic_blocks(df)
    parts = [GENERATED_NOTE]
    parts.append("# Derived variables\n")
    parts.append(
        "Computed (derived) scores for the battery, with the R-style formulas used "
        "to calculate them (`df` = the dataframe holding the raw variables).\n")
    parts.append("\n[← Back to Battery overview](index.md)\n")
    for name, (header, rows) in blocks.items():
        code = name.rstrip("_")
        display = SCALES.get(name, (code, None))[0] if name in SCALES else code
        parts.append(f"\n## {code} — {display}\n")
        for row in rows:
            row = row + [None] * (4 - len(row))
            label, var, _, calc = row[0], row[1], row[2], row[3]
            if pd.isna(label) and pd.isna(var):
                continue
            title = f"**{var}**" if pd.notna(var) else ""
            if pd.notna(label):
                title = f"**{var}** — {label}" if title else f"**{label}**"
            parts.append(f"\n- {title}\n")
            if pd.notna(calc):
                parts.append(f"  ```r\n  {str(calc).strip()}\n  ```\n")
    return "".join(parts)


def render_tasks_page(xl: pd.ExcelFile) -> str:
    df = xl.parse("Tasks", header=None)
    parts = [GENERATED_NOTE]
    parts.append("# Cognitive task variables\n")
    parts.append(
        "Variable-level reference for the cognitive/behavioural tasks in the battery. "
        "These are task outputs (scores, counts), not questionnaire items.\n")
    parts.append("\n[← Back to Battery overview](index.md)\n")

    current = None
    table_open = False
    for _, row in df.iterrows():
        row = row.tolist() + [None] * (4 - df.shape[1])
        first = row[0]
        if pd.isna(first):
            continue
        first = str(first).strip()
        if first in TASKS:  # block header
            name, anchor = TASKS[first]
            parts.append(f"\n## {first} — {name}\n")
            parts.append(f"[Data dictionary entry]({DICT_PAGE}#{anchor})\n\n")
            table_open = False
            current = first
        elif first == "Item_code":
            parts.append("| Variable | Description | Levels | Values |\n|---|---|---|---|\n")
            table_open = True
        elif current and table_open:
            parts.append(
                f"| `{cell(first)}` | {cell(row[1])} | {cell(row[2])} | {cell(row[3])} |\n")
    return "".join(parts)


def render_index(items_blocks: dict) -> str:
    parts = [GENERATED_NOTE]
    parts.append("# Questionnaire Battery — CoVenture & NeuroVenture\n")
    parts.append(
        "Item-level content of every questionnaire in the CoVenture / NeuroVenture "
        "battery: each scale below links to a page listing every question in English "
        "and French, with response options, subscales, and skip rules.\n\n"
        "See also the [derived variables](derived-variables.md) (computed scores and "
        "their formulas), the [cognitive task variables](tasks.md), and the "
        f"[data dictionary]({DICT_PAGE}) (variable naming and where the data lives).\n\n"
        '!!! tip "Finding a question"\n'
        "    Use the search box at the top of any page — the question text of every "
        "item (English and French) is indexed, e.g. searching `drink as a way to "
        "celebrate` jumps straight to the DMQ item.\n")

    parts.append("\n| # | Scale | Code | Items |\n|---|---|---|---|\n")
    for i, (code, block) in enumerate(items_blocks.items(), start=1):
        name = SCALES[code][0]
        parts.append(
            f"| {i} | [{name}](scales/{slug(code)}.md) | `{code}` "
            f"| {len(block['items'])} |\n")

    parts.append("\n## Cognitive tasks\n\n| # | Task |\n|---|---|\n")
    for i, (code, (name, _)) in enumerate(TASKS.items(), start=1):
        parts.append(f"| {i} | [{code} — {name}](tasks.md) |\n")
    return "".join(parts)


def main() -> None:
    if not EXCEL_PATH.exists():
        raise SystemExit(f"Excel file not found: {EXCEL_PATH}")
    xl = pd.ExcelFile(EXCEL_PATH)

    items_blocks = parse_items_sheet(xl)
    missing = set(SCALES) - set(items_blocks)
    if missing:
        print(f"WARNING: no Items-sheet block found for: {sorted(missing)}")

    SCALES_DIR.mkdir(parents=True, exist_ok=True)
    for code, block in items_blocks.items():
        (SCALES_DIR / f"{slug(code)}.md").write_text(
            render_scale_page(code, block), encoding="utf-8")
        print(f"  wrote scales/{slug(code)}.md ({len(block['items'])} items)")

    (OUT_DIR / "derived-variables.md").write_text(
        render_derived_page(xl), encoding="utf-8")
    print("  wrote derived-variables.md")
    (OUT_DIR / "tasks.md").write_text(render_tasks_page(xl), encoding="utf-8")
    print("  wrote tasks.md")
    (OUT_DIR / "index.md").write_text(render_index(items_blocks), encoding="utf-8")
    print("  wrote index.md")
    print("Done.")


if __name__ == "__main__":
    main()
